### ISSUE TITLE
Conflict issue with content view plugin.

### ISSUE THREAD

**Issue by mohammed-qutubuddin** [ahmedkaludi/schema-and-structured-data-for-wp#1501] opened 2021-08-12 06:47 UTC
Reference Ticket URL: https://secure.helpscout.net/conversation/1544818525/202301?folderId=4409869

Schena Reviews shortcode conflict issue with Content view plugin shortcode.

**Comment by Sanjeevsetu** [comment] 2021-09-14 07:07
The issue is no longer valid. I am closing it for now.

**Closed** 2021-09-15 12:14 UTC
