### ISSUE TITLE
Woocommerce category schema has an issue when reviews collection is present

### ISSUE THREAD

**Issue by laharikakuna** [ahmedkaludi/schema-and-structured-data-for-wp#1182] opened 2020-08-28 08:34 UTC
Woocommerce category schema has an issue when reviews collection is present

Ref:https://secure.helpscout.net/conversation/1263519966/150319?folderId=3575684

**Comment by Sanjeevsetu** [comment] 2020-11-03 06:18
The issue is no longer exists. It has been fixed in earlier commits so I am closing it. If user faces the issue. Again, I will re open it

**Closed** 2020-11-10 09:58 UTC
Labels: [P: HIGH], bug
