### ISSUE TITLE
Post format placement is not working fine.

### ISSUE THREAD

**Issue by sardarui** [ahmedkaludi/schema-and-structured-data-for-wp#986] opened 2020-05-07 06:24 UTC
The user is placing 'post format' placement on 'Video' in Video object-schema type but it is not placing correctly.

Ref Ticket: 
https://secure.helpscout.net/conversation/1144530907/124560?folderId=3126461

**Comment by Sanjeevsetu** [comment] 2020-05-13 10:54
I tested this issue on locahost and at user end as well and found that user was doing some wrong in setting up schema. The issue is not valid so I am closing it.

**Comment by ahmedkaludi** [comment] 2020-05-18 16:37
let's discuss before closing

**Closed** 2020-05-19 10:21 UTC
Labels: Need More data, [P: HIGH], bug
