### ISSUE TITLE
Incorrect values are showing by Product schema.

### ISSUE THREAD

**Issue by kunalaharika** [ahmedkaludi/schema-and-structured-data-for-wp#1072] opened 2020-06-17 13:29 UTC
Incorrect values are showing by Product schema. when the user adding the value by custom fields. For example, instead of the brand name, it is showing store name and it also showing incorrect value in the description and condition , availability, and seller organization.

Ref:https://secure.helpscout.net/conversation/1160955209/128951?folderId=3575684

**Comment by Sanjeevsetu** [comment] 2020-06-20 07:05
Waiting for user reply

**Comment by Sanjeevsetu** [comment] 2020-06-24 07:59
Still waiting for user reply

**Comment by Sanjeevsetu** [comment] 2020-06-27 12:27
Still waiting for user reply

**Comment by Sanjeevsetu** [comment] 2020-07-09 06:37
still waiting for user reply

**Comment by Sanjeevsetu** [comment] 2020-07-16 07:03
Since user is not active from long time and the issue is not re created on localhost so i am closing this ticket

**Closed** 2020-07-16 14:53 UTC
Labels: Need More data, [P: HIGH], bug
