### ISSUE TITLE
Excessive number of queries at each page load in admin pages

### ISSUE THREAD

**Issue by LeoKesler** [ahmedkaludi/schema-and-structured-data-for-wp#1227] opened 2020-10-31 12:52 UTC
Hi,
For some reason, I am getting 80+ queries using your plugin every time I load a page at admin shell. This happens in plugin page, comments page, every page at admin shell.  

Can you check and if possible, stop making these calls at every page load in admin ?

Examples:

`SELECT tt.term_id, tt.term_taxonomy_id
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy as tt
ON tt.term_id = t.term_id
WHERE t.slug = 'avvo'
AND tt.taxonomy = 'platform'
ORDER BY t.term_id ASC
LIMIT 1`

`SELECT tt.term_id, tt.term_taxonomy_id
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy as tt
ON tt.term_id = t.term_id
WHERE t.slug = 'dealerrater'
AND tt.taxonomy = 'platform'
ORDER BY t.term_id ASC
LIMIT 1`

`SELECT tt.term_id, tt.term_taxonomy_id
FROM wp_terms AS t
INNER JOIN wp_term_taxonomy as tt
ON tt.term_id = t.term_id
WHERE t.slug = 'tripadvisor'
AND tt.taxonomy = 'platform'
ORDER BY t.term_id ASC
LIMIT 1`

And many more... At first I was thinking my wordpress install was hacked but after disabled all plugins and enabling one by one, I found your plugin had this "issue" .  

Words like **avvo**  , **tripadvisor** and **dealerrater** are found in file   **reviews_setup.php**   inside the function **saswp_insert_platform_terms()** .

Thanks.

![Excessive_DB_Calls_From_Single_Plugin](https://user-images.githubusercontent.com/5854679/97779700-9116d300-1b5e-11eb-9984-7b469363d438.jpg)

**Comment by Sanjeevsetu** [comment] 2020-11-02 13:31
Hi @LeoKesler.

The issue is valid and we have fixed the issue and will push this fixed in next update.

**Closed** 2020-11-10 09:58 UTC
Labels: [P: HIGH], bug
