### ISSUE TITLE
The values of the Seller organization,GTIN13 and other fields are not updating

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/schema-and-structured-data-for-wp#1193] opened 2020-09-05 10:15 UTC
Ref: https://secure.helpscout.net/conversation/1272001865/152334?folderId=2770545

Ref video: https://monosnap.com/file/KQmaY7a5FgJ3RiHZAukv1C7tMeME0E

If the "WooTours" and "YOAST SEO" plugins are active at the user's end then the user is not able to modify the values after clicking on the modified schema option.

At the user end, the issue is occurring in the WordPress 5.5.1 version.

The issue is not recreating on the local.

**Comment by Sanjeevsetu** [comment] 2020-10-15 08:46
Waiting for user reply

**Comment by Sanjeevsetu** [comment] 2020-10-20 10:58
The issue is not being created on localhost and user has not still replied to it. So We are closing it. If we find issue again related to this. We will open it again

**Closed** 2020-10-26 06:26 UTC
Labels: 3rd party compatibility, [P: HIGH], bug
