### ISSUE TITLE
User specefix issue:  When WPML Multilingual CMS plugin is activated,some properties of the modified schema on the product are not rendering 

### ISSUE THREAD

**Issue by TMsravan** [ahmedkaludi/schema-and-structured-data-for-wp#1114] opened 2020-07-09 15:00 UTC
when the WPML Multilingual CMS plugin activated some properties of the modified schema of the product is not rendering in the schema markup values such as name, price, SKU, etc.

The schema on this URL is the modified schema of the product:

https://staging.maxtour.co/tours/grand-canyon-west-hoover-dam-seven-magic-mountains-day-tour/

This is the auto-generated schema: https://staging.maxtour.co/tours/2-day-grand-canyon-antelope-canyon-tour/

This is the specific issue occurring only at the user end.

https://secure.helpscout.net/conversation/1191306124/135312?folderId=2632030

**Comment by Sanjeevsetu** [comment] 2020-07-16 10:35
Waiting for user response to debug the issue

**Comment by Sanjeevsetu** [comment] 2020-07-22 11:24
User is not active anymore and the issue is not being create at our end so we close this ticket

**Closed** 2020-07-23 16:17 UTC
Labels: [P: HIGH], bug
