### ISSUE TITLE
Need to add" Yelp" to social media strategy compatibility.

### ISSUE THREAD

**Issue by Thakur25** [ahmedkaludi/schema-and-structured-data-for-wp#519] opened 2019-09-27 12:52 UTC
Ref:https://secure.helpscout.net/conversation/965759113/86052?folderId=3250553

**Comment by Sanjeevsetu** [comment] 2019-09-28 10:45
This ticket is duplicate of #519 so I am closing it.

**Closed** 2019-09-28 10:45 UTC
