### ISSUE TITLE
location field is not taking value from event calender

### ISSUE THREAD

**Issue by wankhedekomal** [ahmedkaludi/schema-and-structured-data-for-wp#1001] opened 2020-05-14 13:16 UTC
local field not taking any value from event calender and showing warning as name field is recommended if required.
screenshot:
https://prnt.sc/sgp50l

URL: https://www.keymedia.at/termin/filmmusik-gala-hollywood-in-vienna/

Ref: https://secure.helpscout.net/conversation/1161558800/129116?folderId=3257665

**Comment by Sanjeevsetu** [comment] 2020-05-20 11:43
the issue is not tested properly and invalid so I am closing it as I can see the location is automatically coming in json-ld

**Closed** 2020-05-29 09:34 UTC
Labels: [P: HIGH], bug
