### ISSUE TITLE
License activation/deactivation issue

### ISSUE THREAD

**Issue by 77naveenop** [ahmedkaludi/schema-and-structured-data-for-wp#2002] opened 2023-08-24 13:26 UTC
Need to fix license key activation/deactivation issues.

**Comment by Sanjeevsetu** [comment] 2023-09-01 09:21
this is duplicate of https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1998 and has been pushed

**Closed by Sanjeevsetu** 2023-09-01 09:21 UTC
Labels: enhancement, [P: HIGH]
