### ISSUE TITLE
Plugin Conflict Identified

### ISSUE THREAD

**Issue by matthew3102** [ahmedkaludi/schema-and-structured-data-for-wp#1489] opened 2021-07-21 15:22 UTC
While performing updates I found that the release 1.9.82.1 conflicts with Popup Maker version 1.16.2.

This conflict causes the "Popup Settings" tab in Popup Maker to display a message stating there was a Javascript error preventing it from loading and to refer to the console logs for more info. When I checked, there was not any relevant errors. 

I was able to fix the problem by rolling back the 1.9.82.1 update to 1.9.81.

Let me know if there is anything else I can provide. 

(As an aside, your contact form broke when I tried to submit)

![Screen Shot 2021-07-21 at 8 19 42 AM](https://user-images.githubusercontent.com/68600349/126514830-2593f337-7e5c-4e1a-b1d9-986c5442ed06.png)

![Screen Shot 2021-07-21 at 8 20 47 AM](https://user-images.githubusercontent.com/68600349/126514888-549b1785-7d1b-47d1-a11d-a8cc30e7b5a4.png)

**Comment by Sanjeevsetu** [comment] 2021-07-26 10:44
Hi @matthew3102 

Can you trun on debug mode and see what exact error it is??

**Comment by matthew3102** [comment] 2021-07-28 14:56
Hello @Sanjeevsetu,
I turned on debug mode for WordPress + Popup Maker and was not able to find any related errors (see attached image below for console). 

![Popup Maker Settings Tab + Console](https://user-images.githubusercontent.com/68600349/127344421-004ecafe-1cfe-4ba0-b174-a71e7cfcf5e1.png)

There were 2 errors shown at the top of the screen from the WordPress debug mode, however, I deactivated the offending plugin to remove the errors and the Popup Settings tab was unchanged. I also tested with the latest release of 1.9.82.2 and found the issue is still present.

**Comment by Sanjeevsetu** [comment] 2021-08-09 07:16
Hi @matthew3102.

The issue is valid and it has been fixed in this ticket. https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1495. We will push this ticket in next plugin update. Please wait or you can see the changes in the ticket commit.

**Closed** 2021-08-10 11:29 UTC
Labels: bug, [P: HIGH]
