### ISSUE TITLE
Undefined array key - 

### ISSUE THREAD

**Issue by omaluj** [ahmedkaludi/schema-and-structured-data-for-wp#1997] opened 2023-08-17 18:07 UTC
Hello, in server-log we have this PHP Warnings: 

www.omaluj.sk [Thu Aug 17 02:05:27.596695 2023] [php:warn] [pid 27684] [client 37.9.175.155:48928] PHP Warning:  Undefined array key "saswp_product_schema_url" in /data/a/f/afdc94e9-7262-4b22-adbc-2b48ca6fad4e/omaluj.sk/web/wp-content/plugins/schema-and-structured-data-for-wp/output/service.php on line 5314

Do you know, where are the mistake? We are on PHP8.0 and have a lot off PHP Warnings. 

Thanks for reply 
Alex

**Comment by shridhamdeveloper** [comment] 2023-08-24 05:27
This is the duplicate of this below ticket. This issue has been resolved and rolled out in version 1.19
https://github.com/ahmedkaludi/schema-and-structured-data-for-wp/issues/1987

**Closed** 2023-09-01 06:26 UTC
Labels: bug, [P: HIGH], Ready for Review
